return {
--     {
--   "folke/trouble.nvim",
--   branch = "dev", -- IMPORTANT!
--   lazy = false,
--   keys = {
--     {
--       "<leader>xx",
--       "<cmd>Trouble diagnostics toggle<cr>",
--       desc = "Diagnostics (Trouble)",
--     },
--     {
--       "<leader>xX",
--       "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
--       desc = "Buffer Diagnostics (Trouble)",
--     },
--     {
--       "<leader>cs",
--       "<cmd>Trouble symbols toggle focus=false<cr>",
--       desc = "Symbols (Trouble)",
--     },
--     {
--       "<leader>cl",
--       "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
--       desc = "LSP Definitions / references / ... (Trouble)",
--     },
--     {
--       "<leader>xL",
--       "<cmd>Trouble loclist toggle<cr>",
--       desc = "Location List (Trouble)",
--     },
--     {
--       "<leader>xQ",
--       "<cmd>Trouble qflist toggle<cr>",
--       desc = "Quickfix List (Trouble)",
--     },
--   },
--   opts = {},
-- },
--     {
--   "hedyhli/outline.nvim",
--   lazy = false,
--   config = function()
--     -- Example mapping to toggle outline
--     vim.keymap.set("n", "<leader>o", "<cmd>Outline<CR>",
--       { desc = "Toggle Outline" })
--
--     require("outline").setup {
--       -- Your setup opts here (leave empty to use defaults)
--     }
--   end,
-- },
    -- {
    --     "nvim-neo-tree/neo-tree.nvim",
    --     lazy = false,
    --     branch = "v3.x",
    --     dependencies = {
    --         "nvim-lua/plenary.nvim",
    --         "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
    --         "MunifTanjim/nui.nvim",
    --         -- "3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
    --     },
    --     config = true,
    -- },
    -- {
    --     "rcarriga/nvim-dap-ui",
    --     lazy = false,
    --     dependencies = {
    --         "nvim-neotest/nvim-nio",
    --         "mfussenegger/nvim-dap"
    --     },
    --     config = true,
    -- },
    -- {
    --       "nvim-neotest/neotest",
    --       lazy = false,
    --       dependencies = {
    --           "nvim-lua/plenary.nvim",
    --           "antoinemadec/FixCursorHold.nvim"
    --       },
    --     config = true,
    --     opts = {
    -- floating = { max_width = 0.1 },
    -- strategies = { integrated = { width = 1 } },
    --     }
    -- },
    -- {
    --     'goolord/alpha-nvim',
    --     lazy = false,
    --     dependencies = { 'nvim-tree/nvim-web-devicons' },
    --     config = function ()
    --         require'alpha'.setup(require'alpha.themes.startify'.config)
    --     end
    -- },
    -- {
    --     "nvim-tree/nvim-tree.lua",
    --     lazy = false,
    --     dependencies = "mfussenegger/nvim-dap",
    --     config = true,
    -- },
    -- {
    --     "emmanueltouzery/agitator.nvim",
    --     lazy = false,
    -- },
    -- {
    --     "nvim-treesitter/playground",
    --     lazy = false,
    --     config = function ()
    --        require("nvim-treesitter.configs").setup({playground={enable=true}})
    --     end
    -- },
    -- {
    --     "mbbill/undotree",
    --     lazy = false,
    -- config = function ()
    --        require("mbbill/undotree").setup()
    -- end,
    -- },
}
